#!/usr/bin/env node
/**
 * SAL Grid Viewer 빌드 스크립트
 * - grid_records/*.json + stage_gate_records/*.json + index.json을
 *   viewer_json.html에 인라인 데이터로 번들
 * - file:// 프로토콜에서도 동작하도록 함
 *
 * 사용법: node build-viewer.js
 */

const fs = require('fs');
const path = require('path');

const BASE = path.join(__dirname, '..', '3.method', 'json', 'data');
const VIEWER = path.join(__dirname, 'viewer_json.html');

// 1. index.json 읽기
const indexData = JSON.parse(fs.readFileSync(path.join(BASE, 'index.json'), 'utf-8'));

// 2. grid_records 전부 읽기
const gridRecords = {};
const gridDir = path.join(BASE, 'grid_records');
for (const file of fs.readdirSync(gridDir)) {
  if (file.endsWith('.json') && file !== '_TEMPLATE.json') {
    const id = path.basename(file, '.json');
    gridRecords[id] = JSON.parse(fs.readFileSync(path.join(gridDir, file), 'utf-8'));
  }
}

// 3. stage_gate_records 전부 읽기
const gateRecords = {};
const gateDir = path.join(BASE, 'stage_gate_records');
if (fs.existsSync(gateDir)) {
  for (const file of fs.readdirSync(gateDir)) {
    if (file.endsWith('.json') && file !== '_TEMPLATE.json') {
      const id = path.basename(file, '.json');
      gateRecords[id] = JSON.parse(fs.readFileSync(path.join(gateDir, file), 'utf-8'));
    }
  }
}

// 4. demo 데이터 읽기
const demoIndex = (() => {
  const p = path.join(BASE, '_demo', 'index.json');
  return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, 'utf-8')) : null;
})();

const demoRecords = {};
const demoDir = path.join(BASE, '_demo', 'grid_records');
if (fs.existsSync(demoDir)) {
  for (const file of fs.readdirSync(demoDir)) {
    if (file.endsWith('.json')) {
      const id = path.basename(file, '.json');
      demoRecords[id] = JSON.parse(fs.readFileSync(path.join(demoDir, file), 'utf-8'));
    }
  }
}

// 5. 인라인 데이터 블록 생성
const embeddedBlock = `
<!-- ===== EMBEDDED DATA (auto-generated by build-viewer.js) ===== -->
<script>
window.__EMBEDDED_DATA__ = {
  index: ${JSON.stringify(indexData)},
  gridRecords: ${JSON.stringify(gridRecords)},
  gateRecords: ${JSON.stringify(gateRecords)},
  demoIndex: ${JSON.stringify(demoIndex)},
  demoRecords: ${JSON.stringify(demoRecords)}
};
</script>
<!-- ===== END EMBEDDED DATA ===== -->`;

// 6. viewer HTML 읽기
let html = fs.readFileSync(VIEWER, 'utf-8');

// 7. 기존 임베디드 데이터 제거 (재빌드 시)
html = html.replace(/\n<!-- ===== EMBEDDED DATA[\s\S]*?END EMBEDDED DATA ===== -->/g, '');

// 8. </head> 앞에 임베디드 데이터 삽입
html = html.replace('</head>', embeddedBlock + '\n</head>');

// 9. 저장
fs.writeFileSync(VIEWER, html, 'utf-8');

const taskCount = Object.keys(gridRecords).length;
const gateCount = Object.keys(gateRecords).length;
console.log(`✅ 빌드 완료: ${taskCount}개 Task + ${gateCount}개 Gate → viewer_json.html에 인라인 번들`);
